#!/bin/bash -e

echocol() { echo -e "\033[32m*** $@...\033[0m"; }

echocol "Building images"
( ./bin/build ) >/dev/null 2>&1

. ./bin/set_addresses

tests="simple sign"

for t in $tests; do
	echocol "Cleanup running containers"
	( [[ $(docker ps -qa | wc -l) -gt 0 ]] && docker rm -vf $(docker ps -qa) ) >/dev/null 2>&1 || true
	echocol $t
	./test/$t
done
